version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8000:8000"
    env_file:
      - .env  # Isso carrega as variáveis de ambiente do arquivo .env
    networks:
      - app-network

  patient-service:
    build:
      context: ./patient-service
    ports:
      - "8001:8001"
    env_file:
      - .env  # Isso carrega as variáveis de ambiente do arquivo .env
    depends_on:
      - auth-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
